export const QLDC = {
    agencyIssued: '',
    cvNumber: '',
    cvDate: '',
    requestNumber: '',
    documentType: '',
    agencyOwner: '',
    agencyLevelMinistry: [],
    province: [],
    requestType: [],
    documentStatus: '',
    numberAllocated: '',
    cvTakeDate: '',
    transferProductDate: '',
    receiveProductDate: '',
    timeArriveDepartment: '',
    timeDepartmentSxCts: '',
    timeHandoverProduct: '',
    totalTime: '',
    note: '',
    userReceived: '',
};
export const QLDCFILTer = {
    id: '',
    documentStatus: '',
    note: '',
    requestType: [],
    agencyIssued: '',
    from: '',
    to: '',
    superiorAgency: '',
    agencyLevelMinistry: [],
    province: [],
    date: '',
    keyword: ''
};

export const QLDCVALID = {
    agencyIssued: '',
    cvNumber: '',
    cvDate: '',
    requestNumber: '',
    agencyOwner: '',
    requestType: '',
    userReceived: '',
};

export const QLDCEDITMUL = {
    agencyIssued: { value: '', isDelete: false },
    cvNumber: { value: '', isDelete: false },
    cvDate: { value: '', isDelete: false },
    requestNumber: { value: '', isDelete: false },
    documentType: { value: '', isDelete: false },
    agencyOwner: { value: '', isDelete: false },
    agencyLevelMinistry: { value: [], isDelete: false },
    province: { value: [], isDelete: false },
    requestType: { value: [], isDelete: false },
    documentStatus: { value: '', isDelete: false },
    numberAllocated: { value: '', isDelete: false },
    cvTakeDate: { value: '', isDelete: false },
    transferProductDate: { value: '', isDelete: false },
    receiveProductDate: { value: '', isDelete: false },
    timeArriveDepartment: { value: '', isDelete: false },
    timeDepartmentSxCts: { value: '', isDelete: false },
    timeHandoverProduct: { value: '', isDelete: false },
    totalTime: { value: '', isDelete: false },
    note: { value: '', isDelete: false },
    userReceived: { value: '', isDelete: false }
};